package chain

import (
	"encoding/hex"
	"math/big"
	"testing"

	"github.com/ohMySol/eigen-auction/avs/internal/consensus"
)

// Fixture generated by the TS signer (signToBOrder, anvil account #1) — EIP-712 signatures are
// RFC6979-deterministic, so this pins the exact cross-language contract: Go must recover the same
// searcher the TS reference and the contract's _proveFraud would.
const (
	fixtureSigner = "70997970c51812dc3a010c7d01b50e0d17dc79c8"
	fixtureSig    = "39d18f198af43ee4a982c39a75afc33d817cd9e9e88b75206adcbaecbb5ca590766edc538fa3ef01d68015d8b57582aae5499b656e0ec3f1fc19c83f6390ce011b"
	fixtureDigest = "8a868d06fd0b77cc65dd4f19ce4b759551b8a051c0b9cf4bbf5cded06ea79156"
)

func mustHex(t *testing.T, h string) []byte {
	t.Helper()
	b, err := hex.DecodeString(h)
	if err != nil {
		t.Fatalf("bad hex: %v", err)
	}
	return b
}

func fixtureOrder(t *testing.T) (consensus.ToBOrder, [20]byte) {
	var searcher, settler [20]byte
	copy(searcher[:], mustHex(t, fixtureSigner))
	settler[18], settler[19] = 0xde, 0xad // 0x...dead
	var poolID [32]byte
	for i := range poolID {
		poolID[i] = 0x11
	}
	o := consensus.ToBOrder{
		Searcher: searcher,
		PoolID: poolID,
		ZeroForOne: true,
		UseInternal: false,
		QuantityIn: big.NewInt(1_050_000_000_000_000_000),
		QuantityOut: big.NewInt(1_000_000_000_000_000_000),
		ValidForBlock: big.NewInt(100),
	}
	return o, settler
}

func TestRecoverToBOrderSigner(t *testing.T) {
	o, settler := fixtureOrder(t)

	// Digest must match the TS reference (searcher == the actual signer here).
	if d := consensus.OrderDigest(o, settler, big.NewInt(31337)); hex.EncodeToString(d[:]) != fixtureDigest {
		t.Fatalf("digest drift: got %x want %s", d, fixtureDigest)
	}

	got, err := RecoverToBOrderSigner(o, mustHex(t, fixtureSig), settler, big.NewInt(31337))
	if err != nil {
		t.Fatalf("recover: %v", err)
	}
	if hex.EncodeToString(got[:]) != fixtureSigner {
		t.Fatalf("recovered %x, want %s", got, fixtureSigner)
	}
}

func TestRecoverRejectsBadLength(t *testing.T) {
	o, settler := fixtureOrder(t)
	if _, err := RecoverToBOrderSigner(o, []byte{1, 2, 3}, settler, big.NewInt(31337)); err == nil {
		t.Fatal("expected error on short signature")
	}
}
