// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import {Test} from "forge-std/Test.sol";
import {Settler} from "../../src/Settler.sol";
import {ToBOrder} from "../../src/types/ToBOrder.sol";
import {SwapIntent} from "../../src/types/SwapIntent.sol";

/// @notice Golden vectors pinning the on-chain result-hash encoding. The off-chain reference
/// (packages/shared/src/resultHash.ts) asserts the SAME literals in test/resultHash.test.ts, so the
/// two implementations are transitively byte-identical — the property the BLS quorum depends on.
/// If either side changes the encoding, one of the two suites goes red.
///
/// `computeResultHash` is `pure`, so the Settler is deployed with dummy (non-zero) dependency
/// addresses — none are read by the function under test.
contract ResultHashVectorsTest is Test {
    Settler internal settler;

    // Shared fixed inputs — must match resultHash.test.ts exactly. Signatures are omitted because
    // they are excluded from every struct hash.
    bytes32 constant POOL_ID = bytes32(uint256(0x1111111111111111111111111111111111111111111111111111111111111111));
    uint256 constant PRICE = uint256(2000) << 128;

    // Expected hashes, generated by this contract (source of truth) and pasted back as literals so a
    // silent drift on either side fails an assertion rather than passing quietly.
    bytes32 constant EXPECTED_ARB_HASH = 0x623d60f3f55e097ac6780b2e8b72874564238438fdd60c39df059e5a7506a0fb;
    bytes32 constant EXPECTED_INTENTS_RESULT = 0xe7c8f352536e6767c8d9e173dbaa5ed772196e83f2b75dc76e084629119a3f80;
    bytes32 constant EXPECTED_NO_ARB_RESULT = 0x7c8574d6b61317609623f598d388490de3f68f37cdd8ff1494c6ec4a27472cb8;

    function setUp() public {
        settler = new Settler(address(1), address(1), address(1), address(this), 0);
    }

    function _arb() internal pure returns (ToBOrder memory a) {
        a = ToBOrder({
            searcher: address(0xA1),
            poolId: POOL_ID,
            zeroForOne: true,
            useInternal: false,
            quantityIn: 1.05e18,
            quantityOut: 1e18,
            validForBlock: 100,
            signature: ""
        });
    }

    function _intents() internal pure returns (SwapIntent[] memory intents) {
        intents = new SwapIntent[](2);
        intents[0] = SwapIntent({
            user: address(0xB1),
            poolId: POOL_ID,
            zeroForOne: false,
            useInternal: true,
            amountIn: 5e18,
            minAmountOut: 4.9e18,
            nonce: 7,
            deadline: 1_000_000,
            signature: ""
        });
        intents[1] = SwapIntent({
            user: address(0xB2),
            poolId: POOL_ID,
            zeroForOne: true,
            useInternal: false,
            amountIn: 2e18,
            minAmountOut: 1.9e18,
            nonce: 8,
            deadline: 2_000_000,
            signature: ""
        });
    }

    // Emits the canonical hashes so they can be pasted into the EXPECTED_* constants (and resultHash.test.ts).
    function test_emitVectors() public {
        SwapIntent[] memory intents = _intents();
        emit log_named_bytes32("arbStructHash", _arb().toBStructHash());
        emit log_named_bytes32("resultWithArb", settler.computeResultHash(_arb(), PRICE, intents));

        ToBOrder memory empty;
        empty.poolId = POOL_ID;
        emit log_named_bytes32("resultNoArb", settler.computeResultHash(empty, PRICE, intents));
    }

    function test_resultHash_withArb_matchesVector() public view {
        assertEq(_arb().toBStructHash(), EXPECTED_ARB_HASH, "arb struct hash drift");
        assertEq(settler.computeResultHash(_arb(), PRICE, _intents()), EXPECTED_INTENTS_RESULT, "result hash drift");
    }

    function test_resultHash_noArb_matchesVector() public view {
        ToBOrder memory empty;
        empty.poolId = POOL_ID;
        assertEq(settler.computeResultHash(empty, PRICE, _intents()), EXPECTED_NO_ARB_RESULT, "no-arb result hash drift");
    }
}
